name: Call Reusable CI/CD Workflow

on:
  push:
    branches: [node]
  pull_request:
    branches: [node]

jobs:
  run-reusable-workflow:
    uses: codebase-ai/ci_cd_ai_generator/.github/workflows/main.yml@main
    with:
      run_docker_build: true
      push_docker: true
      request_code_review: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
